# Generated by Django 4.1 on 2022-08-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='picture',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
