# Generated by Django 4.1 on 2022-09-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_client_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='period',
            field=models.CharField(max_length=50),
        ),
    ]
