# Generated by Django 4.1 on 2022-09-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_certificates_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
