# Generated by Django 4.1 on 2022-09-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_client_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='link',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='mail',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='profile',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
