# Generated by Django 4.1 on 2022-09-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_client_link_client_mail_client_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='postal',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='adress',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='license',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='client',
            name='nationality',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='town',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
