# Generated by Django 4.1 on 2022-09-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_client_postal_alter_client_adress_alter_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='education',
            name='end',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='education',
            name='start',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='license',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='nationality',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile',
            field=models.CharField(max_length=500),
        ),
    ]
