# Generated by Django 4.1 on 2022-09-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_training_description_training_end_training_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='community',
            name='end',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='community',
            name='start',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='experience',
            name='end',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='experience',
            name='start',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='hobbies',
            name='hobbies',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='internships',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='internships',
            name='end',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='internships',
            name='start',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='languages',
            name='level',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='community',
            name='town',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='experience',
            name='town',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='internships',
            name='town',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
