# Generated by Django 4.1 on 2022-09-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_certificates_description_community_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='level',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
