# Generated by Django 4.1 on 2022-09-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_alter_internships_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internships',
            name='employer',
            field=models.CharField(default='', max_length=60),
        ),
    ]
