# Generated by Django 4.1 on 2022-09-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_alter_skills_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='level',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
