# Generated by Django 4.1 on 2022-09-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_alter_languages_level_alter_skills_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='id',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='id',
        ),
        migrations.RemoveField(
            model_name='training',
            name='id',
        ),
        migrations.AlterField(
            model_name='certificates',
            name='description',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='period',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='license',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='link',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='nationality',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='community',
            name='establishment',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='education',
            name='establishment',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='education',
            name='town',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='experience',
            name='establishment',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='hobbies',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='internships',
            name='description',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='internships',
            name='employer',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='languages',
            name='level',
            field=models.CharField(default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='skills',
            name='level',
            field=models.CharField(default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='training',
            name='establishment',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='training',
            name='training',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
